openapi: 3.0.0
info:
  description: >-
    This service contains content analysis modules. It provides estimation of
    stance detection towards a claim in discussion, and estimation for claim
    veracity. Currently it only supports tweet conversations.
  version: 0.0.2
  title: '[Draft] Co-Inform Content Analysis API'
  contact:
    email: ibaris@uni-koblenz.de
paths:
  /post/stance:
    post:
      summary: Estimates stance of the tweet
      description: It returns stance estimation for given post
      operationId: estimateStance
      parameters:
        - name: tweetId
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Tweet'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StanceResponse'
        '404':
          description: no such a tweet id
  /post/veracity:
    post:
      summary: Estimates how the post is likely to be false
      description: It returns veracity estimation for source post triggers the discussion
      operationId: estimateVeracity
      parameters:
        - name: tweetId
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Tweet'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VeracityResponse'
        '400':
          description: tweet is not source tweet
        '404':
          description: no such a tweet id
components:
  schemas:
    Tweet:
      type: object
      properties:
        tweet_id:
          type: string
    StanceResponse:
      type: object
      properties:
        favor:
          type: number
        against:
          type: number
        na:
          type: number
    VeracityResponse:
      type: object
      properties:
        'false':
          type: number
