openapi: 3.0.0
info:
  description: >-
    This service contains content analysis modules. It provides estimation of
    stance detection towards a claim in discussion, and estimation for claim
    veracity. Currently it only supports tweet conversations.
  version: 0.0.3
  title: '[Draft] Co-Inform Content Analysis API'
  contact:
    email: ibaris@uni-koblenz.de
paths:
  /post/veracity:
    get:
      summary: Estimates post veracity and average of stance towards the post.
      description: Given source post, it detects the stances towards the rumour carried by source post, and then calculates the veracity of the rumour.
      operationId: estimateVeracity
      parameters:
        - name: tweetId
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Tweet'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VeracityResponse'
        '400':
          description: tweet is not source tweet
        '404':
          description: no such a tweet id
components:
  schemas:
    Tweet:
      type: object
      properties:
        tweet_id:
          type: string
    VeracityResponse:
      type: object
      properties:
        'stance_support':
          type: number
        'stance_deny':
          type: number
        'stance_query':
          type: number
        'veracity_prediction':
          type: number
        'veracity_label':
          type: string
