openapi: 3.0.0
info:
  description: >-
    This service contains content analysis modules. It provides estimation of
    stance detection towards a claim in discussion, and estimation for claim's
    veracity. Currently it only supports tweet conversations.
  version: 0.0.1
  title: '[Draft] Co-Inform Content Analysis API'
  contact:
    email: ibaris@uni-koblenz.de
paths:
  /post/stance:
    post:
      summary: Estimates stance of the tweet
      description: It returns stance estimation for given post
      operationId: estimateStance
      parameters:
        - in: string
          name: tweetId
          required: true
          schema:
            $ref: '#/definitions/Tweet'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/StanceResponse'
        '404':
          description: no such a tweet id
  /post/veracity:
    post:
      summary: Estimates how the post is likely to be false
      description: It returns veracity estimation for source post triggers the discussion
      operationId: estimateVeracity
      parameters:
        - in: string
          name: tweetId
          required: true
          schema:
            $ref: '#/definitions/Tweet'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/VeracityResponse'
        '400':
          description: tweet is not source tweet
        '404':
          description: no such a tweet id
definitions:
  Tweet:
    type: object
    properties:
      tweet_id:
        type: string
  StanceResponse:
    type: object
    properties:
      favor:
        type: float
      against:
        type: float
      na:
        type: float
  VeracityResponse:
    type: object
    properties:
      'false':
        type: float
